<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="${packagePath}.mapper.DemoDoMapperExt">
  <resultMap id="BaseResultMap" type="${packagePath}.model.DemoDo">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <id column="ID" jdbcType="INTEGER" property="id" />
    <result column="create_time" jdbcType="TIMESTAMP" property="createTime" />
    <result column="create_owner" jdbcType="VARCHAR" property="createOwner" />
    <result column="update_time" jdbcType="TIMESTAMP" property="updateTime" />
    <result column="update_owner" jdbcType="VARCHAR" property="updateOwner" />
    <result column="optimistic" jdbcType="BIGINT" property="optimistic" />
    <result column="account_code" jdbcType="VARCHAR" property="accountCode" />
    <result column="account_pwd" jdbcType="VARCHAR" property="accountPwd" />
    <result column="cellphone" jdbcType="VARCHAR" property="cellphone" />
    <result column="parent_account_id" jdbcType="VARCHAR" property="parentAccountId" />
    <result column="status" jdbcType="TINYINT" property="status" />
    <result column="app_key" jdbcType="VARCHAR" property="appKey" />
    <result column="GMT_CREATE" jdbcType="TIMESTAMP" property="gmtCreate" />
    <result column="CREATOR" jdbcType="VARCHAR" property="creator" />
    <result column="GMT_MODIFIED" jdbcType="TIMESTAMP" property="gmtModified" />
    <result column="MODIFIER" jdbcType="VARCHAR" property="modifier" />
    <result column="IS_DELETED" jdbcType="CHAR" property="isDeleted" />
  </resultMap>
  <sql id="Example_Where_Clause">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <where>
      <foreach collection="oredCriteria" item="criteria" separator="or">
        <if test="criteria.valid">
          <trim prefix="(" prefixOverrides="and" suffix=")">
            <foreach collection="criteria.criteria" item="criterion">
              <choose>
                <when test="criterion.noValue">
                  and ${r'${criterion.condition}'}
                </when>
                <when test="criterion.singleValue">
                  and ${r'${criterion.condition}'} ${r'#{criterion.value}'}
                </when>
                <when test="criterion.betweenValue">
                  and ${r'${criterion.condition}'} ${r'#{criterion.value}'} and ${r'#{criterion.secondValue}'}
                </when>
                <when test="criterion.listValue">
                  and ${r'${criterion.condition}'}
                  <foreach close=")" collection="criterion.value" item="listItem" open="(" separator=",">
                    ${r'#{listItem}'}
                  </foreach>
                </when>
              </choose>
            </foreach>
          </trim>
        </if>
      </foreach>
    </where>
  </sql>
  <sql id="Update_By_Example_Where_Clause">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <where>
      <foreach collection="example.oredCriteria" item="criteria" separator="or">
        <if test="criteria.valid">
          <trim prefix="(" prefixOverrides="and" suffix=")">
            <foreach collection="criteria.criteria" item="criterion">
              <choose>
                <when test="criterion.noValue">
                  and ${r'${criterion.condition}'}
                </when>
                <when test="criterion.singleValue">
                  and ${r'${criterion.condition}'} ${r'#{criterion.value}'}
                </when>
                <when test="criterion.betweenValue">
                  and ${r'${criterion.condition}'} ${r'#{criterion.value}'} and ${r'#{criterion.secondValue}'}
                </when>
                <when test="criterion.listValue">
                  and ${r'${criterion.condition}'}
                  <foreach close=")" collection="criterion.value" item="listItem" open="(" separator=",">
                    ${r'#{listItem}'}
                  </foreach>
                </when>
              </choose>
            </foreach>
          </trim>
        </if>
      </foreach>
    </where>
  </sql>
  <sql id="Base_Column_List">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    ID, create_time, create_owner, update_time, update_owner, optimistic, account_code,
    account_pwd, cellphone, parent_account_id, status, app_key, GMT_CREATE, CREATOR,
    GMT_MODIFIED, MODIFIER, IS_DELETED
  </sql>
  <select id="selectByExample" parameterType="${packagePath}.model.DemoDoExample" resultMap="BaseResultMap">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <if test="_databaseId == 'oracle'">
      <include refid="OracleDialectPrefix" />
    </if>
    select
    <if test="distinct">
      distinct
    </if>
    <include refid="Base_Column_List" />
    <if test="_databaseId == 'mysql'">
      <include refid="MysqlDialectPrefix" />
    </if>
    from tt_sso_account
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
    <if test="oredCriteria.size != 0">
      and is_deleted = 'n'
    </if>
    <if test="oredCriteria.size == 0">
      where is_deleted = 'n'
    </if>
    <include refid="fullOrgPath" />
    <include refid="owner" />
    <if test="orderByClause != null">
      order by ${r'${orderByClause}'}
    </if>
    <if test="_databaseId == 'oracle'">
      <include refid="OracleDialectSuffix" />
    </if>
    <if test="_databaseId == 'mysql'">
      <include refid="MysqlDialectSuffix" />
    </if>
  </select>
  <select id="selectByPrimaryKey" parameterType="java.lang.Long" resultMap="BaseResultMap">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    select
    <include refid="Base_Column_List" />
    from tt_sso_account
    where ID = ${r'#{id,jdbcType=INTEGER}'}
    and is_deleted = 'n'
  </select>
  <delete id="deleteByExample" parameterType="${packagePath}.model.DemoDoExample">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    delete from tt_sso_account
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
  </delete>
  <select id="countByExample" parameterType="${packagePath}.model.DemoDoExample" resultType="java.lang.Long">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    select count(*) from tt_sso_account
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
    <if test="oredCriteria.size != 0">
      and is_deleted = 'n'
    </if>
    <if test="oredCriteria.size == 0">
      where is_deleted = 'n'
    </if>
    <include refid="fullOrgPath" />
    <include refid="owner" />
  </select>
  <update id="updateByExampleSelective" parameterType="map">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    update tt_sso_account
    <set>
      <if test="record.id != null">
        ID = ${r'#{record.id,jdbcType=INTEGER}'},
      </if>
      <if test="record.createTime != null">
        create_time = ${r'#{record.createTime,jdbcType=TIMESTAMP}'},
      </if>
      <if test="record.createOwner != null">
        create_owner = ${r'#{record.createOwner,jdbcType=VARCHAR}'},
      </if>
      <if test="record.updateTime != null">
        update_time = ${r'#{record.updateTime,jdbcType=TIMESTAMP}'},
      </if>
      <if test="record.updateOwner != null">
        update_owner = ${r'#{record.updateOwner,jdbcType=VARCHAR}'},
      </if>
      <if test="record.optimistic != null">
        optimistic = ${r'#{record.optimistic,jdbcType=BIGINT}'},
      </if>
      <if test="record.accountCode != null">
        account_code = ${r'#{record.accountCode,jdbcType=VARCHAR}'},
      </if>
      <if test="record.accountPwd != null">
        account_pwd = ${r'#{record.accountPwd,jdbcType=VARCHAR}'},
      </if>
      <if test="record.cellphone != null">
        cellphone = ${r'#{record.cellphone,jdbcType=VARCHAR}'},
      </if>
      <if test="record.parentAccountId != null">
        parent_account_id = ${r'#{record.parentAccountId,jdbcType=VARCHAR}'},
      </if>
      <if test="record.status != null">
        status = ${r'#{record.status,jdbcType=TINYINT}'},
      </if>
      <if test="record.appKey != null">
        app_key = ${r'#{record.appKey,jdbcType=VARCHAR}'},
      </if>
      <if test="record.gmtCreate != null">
        GMT_CREATE = ${r'#{record.gmtCreate,jdbcType=TIMESTAMP}'},
      </if>
      <if test="record.creator != null">
        CREATOR = ${r'#{record.creator,jdbcType=VARCHAR}'},
      </if>
      <if test="record.gmtModified != null">
        GMT_MODIFIED = ${r'#{record.gmtModified,jdbcType=TIMESTAMP}'},
      </if>
      <if test="record.modifier != null">
        MODIFIER = ${r'#{record.modifier,jdbcType=VARCHAR}'},
      </if>
      <if test="record.isDeleted != null">
        IS_DELETED = ${r'#{record.isDeleted,jdbcType=CHAR}'},
      </if>
    </set>
    <if test="_parameter != null">
      <include refid="Update_By_Example_Where_Clause" />
    </if>
  </update>
  <update id="updateByExample" parameterType="map">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    update tt_sso_account
    set ID = ${r'#{record.id,jdbcType=INTEGER}'},
    create_time = ${r'#{record.createTime,jdbcType=TIMESTAMP}'},
    create_owner = ${r'#{record.createOwner,jdbcType=VARCHAR}'},
    update_time = ${r'#{record.updateTime,jdbcType=TIMESTAMP}'},
    update_owner = ${r'#{record.updateOwner,jdbcType=VARCHAR}'},
    optimistic = ${r'#{record.optimistic,jdbcType=BIGINT}'},
    account_code = ${r'#{record.accountCode,jdbcType=VARCHAR}'},
    account_pwd = ${r'#{record.accountPwd,jdbcType=VARCHAR}'},
    cellphone = ${r'#{record.cellphone,jdbcType=VARCHAR}'},
    parent_account_id = ${r'#{record.parentAccountId,jdbcType=VARCHAR}'},
    status = ${r'#{record.status,jdbcType=TINYINT}'},
    app_key = ${r'#{record.appKey,jdbcType=VARCHAR}'},
    GMT_CREATE = ${r'#{record.gmtCreate,jdbcType=TIMESTAMP}'},
    CREATOR = ${r'#{record.creator,jdbcType=VARCHAR}'},
    GMT_MODIFIED = ${r'#{record.gmtModified,jdbcType=TIMESTAMP}'},
    MODIFIER = ${r'#{record.modifier,jdbcType=VARCHAR}'},
    IS_DELETED = ${r'#{record.isDeleted,jdbcType=CHAR}'}
    <if test="_parameter != null">
      <include refid="Update_By_Example_Where_Clause" />
    </if>
  </update>
  <update id="updateByPrimaryKeySelective" parameterType="${packagePath}.model.DemoDo">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    update tt_sso_account
    <set>
      <if test="createTime != null">
        create_time = ${r'#{createTime,jdbcType=TIMESTAMP}'},
      </if>
      <if test="createOwner != null">
        create_owner = ${r'#{createOwner,jdbcType=VARCHAR}'},
      </if>
      <if test="updateTime != null">
        update_time = ${r'#{updateTime,jdbcType=TIMESTAMP}'},
      </if>
      <if test="updateOwner != null">
        update_owner = ${r'#{updateOwner,jdbcType=VARCHAR}'},
      </if>
      <if test="optimistic != null">
        optimistic = ${r'#{optimistic,jdbcType=BIGINT}'},
      </if>
      <if test="accountCode != null">
        account_code = ${r'#{accountCode,jdbcType=VARCHAR}'},
      </if>
      <if test="accountPwd != null">
        account_pwd = ${r'#{accountPwd,jdbcType=VARCHAR}'},
      </if>
      <if test="cellphone != null">
        cellphone = ${r'#{cellphone,jdbcType=VARCHAR}'},
      </if>
      <if test="parentAccountId != null">
        parent_account_id = ${r'#{parentAccountId,jdbcType=VARCHAR}'},
      </if>
      <if test="status != null">
        status = ${r'#{status,jdbcType=TINYINT}'},
      </if>
      <if test="appKey != null">
        app_key = ${r'#{appKey,jdbcType=VARCHAR}'},
      </if>
      <if test="gmtCreate != null">
        GMT_CREATE = ${r'#{gmtCreate,jdbcType=TIMESTAMP}'},
      </if>
      <if test="creator != null">
        CREATOR = ${r'#{creator,jdbcType=VARCHAR}'},
      </if>
      <if test="gmtModified != null">
        GMT_MODIFIED = ${r'#{gmtModified,jdbcType=TIMESTAMP}'},
      </if>
      <if test="gmtModified == null">
        <if test="_databaseId == 'oracle'">
          GMT_MODIFIED = sysdate,
        </if>
        <if test="_databaseId == 'mysql'">
          GMT_MODIFIED = current_timestamp,
        </if>
      </if>
      <if test="modifier != null">
        MODIFIER = ${r'#{modifier,jdbcType=VARCHAR}'},
      </if>
      <if test="modifier == null">
        MODIFIER = 'system',
      </if>
      <if test="isDeleted != null">
        IS_DELETED = ${r'#{isDeleted,jdbcType=CHAR}'},
      </if>
    </set>
    where ID = ${r'#{id,jdbcType=INTEGER}'}
    and is_deleted = 'n'
  </update>
  <insert databaseId="mysql" id="insertSelective" keyProperty="id" parameterType="${packagePath}.model.DemoDo" useGeneratedKeys="true">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    insert into tt_sso_account
    <trim prefix="(" suffix=")" suffixOverrides=",">
      ID,
      <if test="isDeleted == null">
        IS_DELETED,
      </if>
      <if test="creator == null">
        CREATOR,
      </if>
      <if test="modifier == null">
        MODIFIER,
      </if>
      <if test="gmtModified == null">
        GMT_MODIFIED,
      </if>
      <if test="gmtCreate == null">
        GMT_CREATE,
      </if>
      <if test="createTime != null">
        create_time,
      </if>
      <if test="createOwner != null">
        create_owner,
      </if>
      <if test="updateTime != null">
        update_time,
      </if>
      <if test="updateOwner != null">
        update_owner,
      </if>
      <if test="optimistic != null">
        optimistic,
      </if>
      <if test="accountCode != null">
        account_code,
      </if>
      <if test="accountPwd != null">
        account_pwd,
      </if>
      <if test="cellphone != null">
        cellphone,
      </if>
      <if test="parentAccountId != null">
        parent_account_id,
      </if>
      <if test="status != null">
        status,
      </if>
      <if test="appKey != null">
        app_key,
      </if>
      <if test="gmtCreate != null">
        GMT_CREATE,
      </if>
      <if test="creator != null">
        CREATOR,
      </if>
      <if test="gmtModified != null">
        GMT_MODIFIED,
      </if>
      <if test="modifier != null">
        MODIFIER,
      </if>
      <if test="isDeleted != null">
        IS_DELETED,
      </if>
    </trim>
    <trim prefix="values (" suffix=")" suffixOverrides=",">
      ${r'#{id,jdbcType=INTEGER}'},
      <if test="isDeleted == null">
        'n',
      </if>
      <if test="creator == null">
        'system',
      </if>
      <if test="modifier == null">
        'system',
      </if>
      <if test="gmtModified == null">
        current_timestamp,
      </if>
      <if test="gmtCreate == null">
        current_timestamp,
      </if>
      <if test="createTime != null">
        ${r'#{createTime,jdbcType=TIMESTAMP}'},
      </if>
      <if test="createOwner != null">
        ${r'#{createOwner,jdbcType=VARCHAR}'},
      </if>
      <if test="updateTime != null">
        ${r'#{updateTime,jdbcType=TIMESTAMP}'},
      </if>
      <if test="updateOwner != null">
        ${r'#{updateOwner,jdbcType=VARCHAR}'},
      </if>
      <if test="optimistic != null">
        ${r'#{optimistic,jdbcType=BIGINT}'},
      </if>
      <if test="accountCode != null">
        ${r'#{accountCode,jdbcType=VARCHAR}'},
      </if>
      <if test="accountPwd != null">
        ${r'#{accountPwd,jdbcType=VARCHAR}'},
      </if>
      <if test="cellphone != null">
        ${r'#{cellphone,jdbcType=VARCHAR}'},
      </if>
      <if test="parentAccountId != null">
        ${r'#{parentAccountId,jdbcType=VARCHAR}'},
      </if>
      <if test="status != null">
        ${r'#{status,jdbcType=TINYINT}'},
      </if>
      <if test="appKey != null">
        ${r'#{appKey,jdbcType=VARCHAR}'},
      </if>
      <if test="gmtCreate != null">
        ${r'#{gmtCreate,jdbcType=TIMESTAMP}'},
      </if>
      <if test="creator != null">
        ${r'#{creator,jdbcType=VARCHAR}'},
      </if>
      <if test="gmtModified != null">
        ${r'#{gmtModified,jdbcType=TIMESTAMP}'},
      </if>
      <if test="modifier != null">
        ${r'#{modifier,jdbcType=VARCHAR}'},
      </if>
      <if test="isDeleted != null">
        ${r'#{isDeleted,jdbcType=CHAR}'},
      </if>
    </trim>
  </insert>
  <insert databaseId="oracle" id="insertSelective" parameterType="${packagePath}.model.DemoDo">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Long">
      SELECT LAST_INSERT_ID()
    </selectKey>
    insert into tt_sso_account
    <trim prefix="(" suffix=")" suffixOverrides=",">
      ID,
      <if test="isDeleted == null">
        IS_DELETED,
      </if>
      <if test="creator == null">
        CREATOR,
      </if>
      <if test="modifier == null">
        MODIFIER,
      </if>
      <if test="gmtModified == null">
        GMT_MODIFIED,
      </if>
      <if test="gmtCreate == null">
        GMT_CREATE,
      </if>
      <if test="createTime != null">
        create_time,
      </if>
      <if test="createOwner != null">
        create_owner,
      </if>
      <if test="updateTime != null">
        update_time,
      </if>
      <if test="updateOwner != null">
        update_owner,
      </if>
      <if test="optimistic != null">
        optimistic,
      </if>
      <if test="accountCode != null">
        account_code,
      </if>
      <if test="accountPwd != null">
        account_pwd,
      </if>
      <if test="cellphone != null">
        cellphone,
      </if>
      <if test="parentAccountId != null">
        parent_account_id,
      </if>
      <if test="status != null">
        status,
      </if>
      <if test="appKey != null">
        app_key,
      </if>
      <if test="gmtCreate != null">
        GMT_CREATE,
      </if>
      <if test="creator != null">
        CREATOR,
      </if>
      <if test="gmtModified != null">
        GMT_MODIFIED,
      </if>
      <if test="modifier != null">
        MODIFIER,
      </if>
      <if test="isDeleted != null">
        IS_DELETED,
      </if>
    </trim>
    <trim prefix="values (" suffix=")" suffixOverrides=",">
      ${r'#{id,jdbcType=INTEGER}'},
      <if test="isDeleted == null">
        'n',
      </if>
      <if test="creator == null">
        'system',
      </if>
      <if test="modifier == null">
        'system',
      </if>
      <if test="gmtModified == null">
        sysdate,
      </if>
      <if test="gmtCreate == null">
        sysdate,
      </if>
      <if test="createTime != null">
        ${r'#{createTime,jdbcType=TIMESTAMP}'},
      </if>
      <if test="createOwner != null">
        ${r'#{createOwner,jdbcType=VARCHAR}'},
      </if>
      <if test="updateTime != null">
        ${r'#{updateTime,jdbcType=TIMESTAMP}'},
      </if>
      <if test="updateOwner != null">
        ${r'#{updateOwner,jdbcType=VARCHAR}'},
      </if>
      <if test="optimistic != null">
        ${r'#{optimistic,jdbcType=BIGINT}'},
      </if>
      <if test="accountCode != null">
        ${r'#{accountCode,jdbcType=VARCHAR}'},
      </if>
      <if test="accountPwd != null">
        ${r'#{accountPwd,jdbcType=VARCHAR}'},
      </if>
      <if test="cellphone != null">
        ${r'#{cellphone,jdbcType=VARCHAR}'},
      </if>
      <if test="parentAccountId != null">
        ${r'#{parentAccountId,jdbcType=VARCHAR}'},
      </if>
      <if test="status != null">
        ${r'#{status,jdbcType=TINYINT}'},
      </if>
      <if test="appKey != null">
        ${r'#{appKey,jdbcType=VARCHAR}'},
      </if>
      <if test="gmtCreate != null">
        ${r'#{gmtCreate,jdbcType=TIMESTAMP}'},
      </if>
      <if test="creator != null">
        ${r'#{creator,jdbcType=VARCHAR}'},
      </if>
      <if test="gmtModified != null">
        ${r'#{gmtModified,jdbcType=TIMESTAMP}'},
      </if>
      <if test="modifier != null">
        ${r'#{modifier,jdbcType=VARCHAR}'},
      </if>
      <if test="isDeleted != null">
        ${r'#{isDeleted,jdbcType=CHAR}'},
      </if>
    </trim>
  </insert>
  <update databaseId="oracle" id="deleteByPrimaryKey" parameterType="${packagePath}.model.DemoDo">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    update tt_sso_account set is_deleted = 'y',modifier=${r'#{modifier,jdbcType=VARCHAR}'},gmt_Modified=sysdate where ID = ${r'#{id,jdbcType=NUMERIC}'}
  </update>
  <update databaseId="mysql" id="deleteByPrimaryKey" parameterType="${packagePath}.model.DemoDo">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    update tt_sso_account set is_deleted = 'y',modifier=${r'#{modifier,jdbcType=VARCHAR}'},gmt_Modified=current_timestamp where ID = ${r'#{id,jdbcType=BIGINT}'}
  </update>
  <sql id="OracleDialectPrefix">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <if test="page != null">
      select * from ( select row_.*, rownum rownum_ from (
    </if>
  </sql>
  <sql id="OracleDialectSuffix">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <if test="page != null">
      <![CDATA[ ) row_ ) where rownum_ >= ${r'#{page.begin}'} and rownum_ < ${r'#{page.end}'} ]]>
    </if>
  </sql>
  <sql id="MysqlDialectPrefix">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <if test="page != null">
      from tt_sso_account where id in ( select id from ( select id
    </if>
  </sql>
  <sql id="MysqlDialectSuffix">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <if test="page != null">
      <![CDATA[ limit ${r'#{page.begin}'}, ${r'#{page.length}'} ) as temp_page_table) ]]>
    </if>
  </sql>
  <sql id="fullOrgPath">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <if test="fullOrgPath != null">
      and full_org_path like CONCAT(${r'#{fullOrgPath}'}, '%')
    </if>
  </sql>
  <sql id="owner">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Sun Jun 21 16:28:12 CST 2020.
    -->
    <if test="owner != null">
      and owner =${r'#{owner,jdbcType=VARCHAR}'}
    </if>
  </sql>
</mapper>