package com.spring.simple.development.demo.model;

import com.alibaba.lava.base.LavaDo;
import lombok.Data;

@Data
public class DemoDo extends LavaDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.name
     *
     * @mbg.generated Wed Jan 15 19:02:54 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.value
     *
     * @mbg.generated Wed Jan 15 19:02:54 CST 2020
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.value2
     *
     * @mbg.generated Wed Jan 15 19:02:54 CST 2020
     */
    private String value2;

    @Override
    public String getBoQualifiedIntfName() {
        return "com.spring.simple.development.demo.service.DemoBo";
    }
}