package com.spring.simple.development.demo.model;

import com.alibaba.lava.base.LavaDo;
import io.swagger.annotations.ApiModel;
import lombok.Data;

@Data
@ApiModel(value = "demoDo", description = "DemoDo用户")
public class DemoDo extends LavaDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.name
     *
     * @mbg.generated Mon Feb 10 18:19:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.value
     *
     * @mbg.generated Mon Feb 10 18:19:55 CST 2020
     */
    private String value;

    @Override
    public String getBoQualifiedIntfName() {
        return "com.spring.simple.development.demo.service.DemoBo";
    }
}